spring:
  application:
    name: registry
  cloud:
    # Fix [WARN] You already have RibbonLoadBalancerClient on your classpath.
    # It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend
    # switching to BlockingLoadBalancerClient instead. In order to use it, set the
    # value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or
    # remove spring-cloud-starter-netflix-ribbon from your project.
    loadbalancer.ribbon.enabled: false

info:
  app.name: ${spring.application.name}

eureka:
  client:
    register-with-eureka: ${EUREKA_SERVER_REGISTER:false}
    fetch-registry: ${EUREKA_SERVER_FETCH_REGISTRY:false}

